### ISSUE TITLE
CPU Consumption in a dormant system

### ISSUE THREAD

**Issue by mr-j0nes** [RaftLib/RaftLib#163]
Hello Jonathan,

many years have passed since our last communication. Hope this message finds you well.

Recently I have come back to the one project of mine where I use Raftlib. Basically, I am trying to understand the CPU consumption when the streams are in dormant state. With that I mean when the system has no work and just sits there waiting for something to do.

I have another project where I have the same situation and with same number of threads, but the CPU is barely used. The project is an API server, and the threads are from the HTTP server waiting for any connection to come in. All threads are in sleeping state.

On my Raftlib project, my input kernels just return raft::proceed as they have nothing to do. The CPU consumption is more than expected (around 350% in a 4 threads/2 core system). All threads are in running state, even those of non-input kernels. And the CPU fan starts going as soon as I start up the streams.

So, the questions is, is there any way I can reduce the CPU consumption? At least for those kernels that are not input?

## Steps To Reproduce
In the file [poc.cpp](https://github.com/RaftLib/RaftLib/blob/master/examples/simple/poc.cpp#L39)
Just replace line 39 from this:
    ` if (i > 20) return (raft::stop);`
to this:
    ` if (i > 20) return (raft::proceed);`

Using latest version from master, hash: 160f8808f596ccfc4c613a5009b682c63f66254d

## Screenshots
Output of "htop"
![image](https://user-images.githubusercontent.com/24613872/189732676-adfb335f-c7b1-4768-9a20-01216c9392d9.png)

## Platform
Ubuntu 18.04 Intel I7-7567U

**Comment by jheo4** [comment]
Hi @jonathan-beard @mr-j0nes.
I also faced similar issues, and have some related questions about the RaftLib scheduler/kernel execution.

- How does the scheduler/kernel work when there is no input from a port?
  - Does a RaftLib kernel work with busy waiting? If so, the high CPU usage can be caused by checking the port at a very high frequency.
  - If the kernel execution is scheduled by a scheduler, how does the scheduler schedule a kernel when messages are generated from the source at a low frequency? Does it keep scheduling and executing the kernel at a very high rate? If so, the CPU usage might be caused by this continuous scheduling and kernel execution (the kernel would do nothing though).

I think one hacky solution is to put some buffer time between the busy waiting (the first case) or prevent the scheduling when the kernel was previously scheduled in some time duration (the second case).

**Comment by jheo4** [comment]
Hi @mr-j0nes @jonathan-beard.

From this morning, I have been having fun with the RaftLib codes and found out that the current simplescheduler causes this issue. Please check my PR and reply if you have any comments/thoughts.

Thanks,

**Comment by mr-j0nes** [comment]
Hello @jheo4 ,
sorry it took me so long to reply to this thread. I wanted to thank you for the change. It really improved the performance on idle.
Best regards.
