### ISSUE TITLE
prefetch buffer control

### ISSUE THREAD

**Issue by leinxx** [RaftLib/RaftLib#26]
Is there anyway to control the port buffer size? For example. I have one kernel to download data and another kernel to process the data. Downloading (prefetching) is much faster than processing which uses a lot of disk space. Is there a way to control the prefetched (port) buffer size and halt the downloading kernel when port buffer is full?

**Comment by jonathan-beard** [comment]
Hi. So there will be a much nicer way to do this in the beta release using the inline stream connectors. The best way to do it in the main line, however is using the old link functions which look like:
 
```cpp
      kernel_pair_t link( raft::kernel *a, 
                          const std::string a_port, 
                          raft::kernel *b, 
                          const std::string b_port,
                          const std::size_t buffer = 0 )
```
There are combinations for convenience where "a" only has one output port and "b" only has one input port that omit the string port name. The buffer variable is of course the size of the buffer in number of elements of the port type. Once the port fills up, the source (in your case the DL kernel) will block until the processing kernel(s) have emptied out some data. On the next beta release I should have <tt>mwait</tt> for x86 and <tt>sev/wfe</tt> ready to go so that when blocked we can be a bit more efficient than yielding/pausing. 

For a full example with the syntax active in the main branch (I included a new testcase as well that shows this code in full ( <tt>fixedAllocate.cpp</tt> ). 

```cpp
int
main( int argc, char **argv )
{
   int count( 1000 );
   if( argc == 2 )
   {
      count = atoi( argv[ 1 ] );
   }
   using type_t = std::int64_t;
   using gen = raft::test::generate< type_t >;
   using sum = Sum< type_t, type_t, type_t >;
   using p_out = raft::print< type_t, '\n' >;
   gen a( count ), b( count );
   sum s;
   p_out print;

   raft::map m;
   
   /** set a >> s[ "input_b" ] as a fixed size of 10 **/
   m.link( &a, &s, "input_a", 10 );
   
   m += b >> s[ "input_b" ];
   m += s >> print;
   m.exe();
   
   return( EXIT_SUCCESS );
}
```

It looks like there is a small bug in the <tt>dynalloc.cpp</tt> file which caused the dynamic allocator to try to re-allocate the buffer it the utilization is to high. It's throttled, but this isn't the intended behavior. I'll applied the fix before responding and tested it out on OS X/Linux. Bug patch will also be applied to dev branch so it won't crop up again in the beta release. 

The longer term solution to fixing buffers will be a stream modifier, we're still debating internally about the best composition...but we've narrowed it down to two candidates which both seem relatively intuitive. 

Out of curiosity, we set memory alignment based on a macro for a binary compilation. Right now that macro defaults to 16 byte alignment for all allocations on machines without vector alignment, and 32-byte for machines with wider vectors...would that be a useful thing to set manually? 

Also curious, there is a link variable to manually set the buffer pointer itself if needed. Would you find use of that if given the expressiveness to manually hand the stream a pre-allocated pointer to use? 

Either way, let me know if you have any issues with the older link function above. I tested it to make sure it still works and fixed the one bug I found. 

Thanks for using RaftLib!!
-J
