### ISSUE TITLE
How to "ZeroCopy" from source to destination ?

### ISSUE THREAD

**Issue by mr-j0nes** [RaftLib/RaftLib#32]
Hi there,

Great job with the lib. 
Let's say I have A >> B >> C. Is it possible to allocate data on A and just release it on C ?
I don't seem to understand how to do it ..

Thanks..
PS: in a different post I provided a "poc.cpp" where I show (more or less) what I want to do ..

**Comment by jonathan-beard** [comment]
This one probably needs more documentation. So for primitive types (e.g., int) the memory for allocate is allocated directly on the outbound queue vs. creating on the local stack and copying to the output queue as in most frameworks. Depending on the size of the object, determined by the template (https://github.com/RaftLib/RaftLib/blob/dev/raftinc/alloc_traits.tcc) the allocation occurs in a few different ways. The simplest way to explain is if its a primitive type it is allocated directly on the output queue. If it's bigger than a cache line then it's allocated externally (right now using malloc). For large objects the pointer should be passed no matter what from a->b->c. There's a garbage collector that operates on these to ensure that a pushed object isn't deallocated if it's still in use.

The main reason the data is allocated directly on the output queue is that we can also vectorize operations on the primitive types when possible. I haven't yet implemented all the classes needed to do so....unfortunately the compiler can't figure out that the data coming off the port will be aligned, so these have to be hand coded either using intrinsics or asm direct. 

So for the example you gave, if we have an object bigger than a cache line, it can be passed all the way through to C. If the object is smaller, it'll go from a->b, then b->c. There will be no actual allocations since the memory is dedicated to the FIFO. For all objects with constructors and all others, the in place constructor is called or the data is ready to use in-place. Does that help a bit? I'll try to update the docs, but feedback on the explanation would be useful. 

Thanks!

**Comment by jonathan-beard** [comment]
Here's a complete example using the code you sent. I did find a but in the "allocate_s" function enable_if's. I'll fix that shortly. In the interim, the allocate functions is just fine. Compile with
```bash
clang++ `pkg-config --libs raftlib` -DZEROCPY=1 poc.cpp `pkg-config --cflags raftlib`
```
If you've manually installed the .pc file (assuming linux or mac) for zero copy or no "-DZEROCPY=1 " if you want to get the standard templates for inline allocation. All this is doing is changing the size and then that specifies the type of handling the FIFO does at compile time for the type. 

```cpp
/**
 *
 * Proof of concept Raftlib
 *
 * Want to have a 3 kernels stream which produces and sends 10 numbers down the stream.
 * The 10 numbers should be created by the first kernel and destroyed by the last.
 *
 */
#include <raft>
#include <raftio>


struct big_t
{
    int i;
    std::uintptr_t start;
#ifdef ZEROCPY
    char padding[ 100 ];
#else
    char padding[ 32 ];
#endif
};



/**
 * Producer: sends down the stream numbers from 1 to 10
 */
class A : public raft::kernel
{
private:
    int i   = 0;
    int cnt = 0;

public:
    A() : raft::kernel()
    {
        output.addPort< big_t >("out");
    }

    virtual raft::kstatus run()
    {
        i++;

        if ( i <= 10 ) 
        {
            auto &c( output["out"].allocate< big_t >() );
            c.i = i;
            c.start = reinterpret_cast< std::uintptr_t >( &(c.i) );
            output["out"].send();
        }

        if ( i > 20 ) 
        {
            return (raft::stop);
        }
        return (raft::proceed);
    };
};

/**
 * Processor: It simmulates a process with the input numbers
 */
class B : public raft::kernel
{
private: 
    int cnt = 0;
public:
    B() : raft::kernel()
    {
        input.addPort<big_t>("in");
        output.addPort<big_t>("out");
    }

    virtual raft::kstatus run()
    {
        auto &a( input[ "in" ].peek< big_t >());
        input[ "in" ].recycle( 1 );
        output[ "out" ].push( a );
        return (raft::proceed);
    }
};

/**
 * Consumer: takes the number from input and dumps it to the console
 */
class C : public raft::kernel
{
private:
    int cnt = 0;
public:
    C() : raft::kernel()
    {
        input.addPort< big_t >("in");
    }

    virtual raft::kstatus run()
    {
        auto &a( input[ "in" ].peek< big_t >() );
        std::cout << a.i << " - " << std::hex << a.start << " - " << std::hex <<  
            reinterpret_cast< std::uintptr_t >( &a.i ) << "\n";
        input[ "in" ].recycle(1);
        return (raft::proceed);
    }
};

int main()
{
    A a;
    B b;
    C c;

    raft::map m;
    
    // m += a >> b; // Core dump
    m += a >> b >> c;

    m.exe();

    return( EXIT_SUCCESS );
}
```

Output with zero copy looks like this (iteration - start addy - end addy):

```bash
1 - 7ff157e00460 - 7ff157e00460
2 - 7ff157e004e0 - 7ff157e004e0
3 - 7ff157e00560 - 7ff157e00560
4 - 7ff157e005e0 - 7ff157e005e0
5 - 7ff157e00660 - 7ff157e00660
6 - 7ff157e006e0 - 7ff157e006e0
7 - 7ff157e00760 - 7ff157e00760
8 - 7ff157e007e0 - 7ff157e007e0
9 - 7ff157e00860 - 7ff157e00860
a - 7ff157e008e0 - 7ff157e008e0
```

**Comment by jonathan-beard** [comment]
Fixed "allocate_s" for external allocate. 

Added this definition to _fifo.hpp_ 

```cpp
   template < class T,
              class ... Args,
              typename std::enable_if< ext_alloc< T >::value >::type* = nullptr > 
   auto allocate_s( Args&&... params ) -> autorelease< T, allocatetype >
   {
      T **ptr( nullptr );
      /** call blocks till an element is available **/
      local_allocate( (void**) &ptr );
      *ptr = new T( std::forward< Args >( params )... );
      return( autorelease< T, allocatetype >( 
         reinterpret_cast< T* >( *ptr ), (*this) ) );
   }
```

Will push tomorrow if it passes regression. Also adding a test case to the regression suite to make sure this doesn't get broken again. Thanks for the catch!

**Comment by jonathan-beard** [comment]
Just committed "9001d480305843ad51e4a1cb7ed9dee2a73978ff" to fix the bug I found while responding to this one. Also considering bulk zero copy for primitive types...will write up in wiki and send around for comment.

**Comment by mr-j0nes** [comment]
Thanks Jonathan for the explanation and for the example. I have updated the library and tested the examples. Everything is clear now..

**Comment by jonathan-beard** [comment]
Not quite....I'd love your opinion on if zero copy for primitive times
would be worth it, and an example. I can see in the example you gave if I
can determine bulk windows that will remain live that it could be made
efficient to pass elements through, I just haven't found a case where that
was general enough to code up.
