### ISSUE TITLE
What's the difference between returning raft::proceed and not.

### ISSUE THREAD

**Issue by mr-j0nes** [RaftLib/RaftLib#39]
Imagine 2 scenarios:

1)
a. Producer sends an object down the stream
b. Sleeps 10 seconds
c. Returns raft::proceed
d. The library calls my producer again
e. Back to (a)

2)
a. Producer in a loop while(!terminate)
b. Sends an object down the stream and sleeps 10 seconds.
c. Back to (a)

Is there any difference between 1 and 2 ?

**Comment by jonathan-beard** [comment]
The difference between 
```cpp
raft::proceed
```
and 
```cpp
raft::stop
```
is really in the way the runtime handles the scheduling of the function that is the calling kernel. If the kernel returns 
```cpp
raft::stop
```
it is removed from being scheduled further. In example 1 from above, if the producer returns _stop_ it is not going to be called again, ever by the scheduler. Calling proceed tells the runtime to call the kernel again. You can think of it as a "schedule me, until i return stop." The real difference, IMHO, between example 1 & 2, is that 2 takes the control from the runtime and places it in the hands of the programmer. That means, that if the runtime decides to do something else with the quanta it'd have to forcibly preempt during the execution (which wouldn't be good, and it won't), or just wait till 2 is finished. Once example 2 has exhausted the space on its output ports and it blocks, the runtime will (and does) yield so that other kernels can pick up the slack. So...in a sense, example 1 is the more optimal way to code it, example 2 would leave fewer scheduling avenues open to the runtime. Does that answer the question? Calling stop when does, also sets in place the logic to begin application shutdown (well, map shutdown). Once all producers have signaled stop, then the stop condition can be propagated to consumers down the chain to do an orderly shutdown (which is why most of the intermediate kernels in an application simply return raft::proceed). Does this answer the question?

**Comment by mr-j0nes** [comment]
Yes you did answer many questions actually. For the first above, now I see that option 1 is better than option 2. Actually the existence of raft::proceed denotes it already. 
Other suspicions about raft::stop that I had in the back of my mind got confirmed also.
Thanks for the answers closing issue..
