### ISSUE TITLE
Does the peek() function provide any timeout ?

### ISSUE THREAD

**Issue by mr-j0nes** [RaftLib/RaftLib#44]
Imagine following scenario:

`m += a1 >> c["in1"];`
`m += a2 >> c["in2"];`

`c` loops ports `in1` and `in2` to consume the corresponding messages from `a1` and `a2`. Now imagine producer `a1` does not produce anything. Even though `a1` delivers raft::proceed, `c` gets stuck waiting for a message from it.
I searched in the documentation but could not find any timeout flag for peek(). 
How would you recommend proceeding ?

Here a little poc:
``` c++
/**
 *
 * Proof of concept Raftlib
 *
 * Want to have 1 consumer and 2 producers. The consumer should timeout and continue with next
 * producer if first producer does not produce..
 *
 */
#include <raft>
#include <raftio>


struct big_t
{
    int i;
    std::uintptr_t start;
#ifdef ZEROCPY
    char padding[ 100 ];
#else
    char padding[ 32 ];
#endif
};



/**
 * Producer: sends down the stream numbers from 1 to 10
 */
class A1 : public raft::kernel
{
private:
    int i   = 0;
    int cnt = 0;

public:
    A1() : raft::kernel()
    {
        output.addPort< big_t >("out");
    }

    virtual raft::kstatus run()
    {
        i++;

        if ( i <= 10 ) 
        {
            auto &c( output["out"].allocate< big_t >() );
            c.i = i;
            c.start = reinterpret_cast< std::uintptr_t >( &(c.i) );
            output["out"].send();
        }
        else 
        {
            return (raft::stop);
        }

        return (raft::proceed);
    };
};

class A2 : public raft::kernel
{
private:
    int i   = 0;
    int cnt = 0;

public:
    A2() : raft::kernel()
    {
        output.addPort< big_t >("out");
    }

    virtual raft::kstatus run()
    {
        i++;

        if ( i <= 10 ) 
        {
            NULL; //
            sleep(1);
        }
        else 
        {
            return (raft::stop);
        }

        return (raft::proceed);
    };
};

/**
 * Consumer: takes the number from input and dumps it to the console
 */
class C : public raft::kernel
{
private:
    int cnt = 0;
public:
    C() : raft::kernel()
    {
        input.addPort< big_t >("in1");
        input.addPort< big_t >("in2");
    }

    virtual raft::kstatus run()
    {
        if (cnt % 2 == 0)
        {
            try {
                std::cout << "in1: " << cnt << "\n";
                auto &a( input[ "in1" ].peek< big_t >() );
                std::cout << std::dec << a.i << " - " << std::hex << a.start << " - " << std::hex <<  
                    reinterpret_cast< std::uintptr_t >( &a.i ) << "\n";
                input[ "in1" ].recycle(1);
            }
            catch(ClosedPortAccessException& cpae)
            {
                NULL; // continue
            }
        }
        else
        {
            try {
                std::cout << "in2: " << cnt << "\n";
                auto &a( input[ "in2" ].peek< big_t >() );
                std::cout << "yeap\n";
                std::cout << std::dec << a.i << " - " << std::hex << a.start << " - " << std::hex <<  
                    reinterpret_cast< std::uintptr_t >( &a.i ) << "\n";
                input[ "in2" ].recycle(1);
            }
            catch(ClosedPortAccessException& cpae)
            {
                NULL; // continue
            }
        }
        ++cnt;
        return (raft::proceed);
    }
};

int main()
{
    A1 a1;
    A2 a2;
    C c;

    raft::map m;
    
    m += a1 >> c["in1"];
    m += a2 >> c["in2"];

    m.exe();

    return( EXIT_SUCCESS );
}
```

**Comment by jonathan-beard** [comment]
The first thing that is apparent is that RaftLib is in need of a  _raft::sleep_ that corresponds to the underlying runtime implementation. For instance, if I'm using [qthreads](http://www.cs.sandia.gov/qthreads/), I  definitely don't want to call sleep as it would sleep the entire kernel visible thread (with my own stack swapping  routine the same). So, that's the first thing. That abstraction needs to be provided. Likely with some form of the  _std::duration_ spec for time vs. the clock_t or some other struct.  

RaftLib currently doesn't provide a timeout for the _peek_ function.  I could easily add one, however, lets see if the current API  supports what you need. Looking at the structure of **C** I see that you've caught the closed port exception that is called once the producer attached to **in1** shuts down. That's the right thing to do. There's also a _size()_ function for each port that will return the number of elements currently on that input  stream. If it is zero then you could skip the call. That will also not trigger the closed port exception, which could be  faster.  

The _peek()_ implementation itself will call the runtime  specific yield for this kernel if no data is available, so in that respect, it's not wasting compute cycles spinning  on a slow producer. The issue as you point out, is that the consumer **C** would spin waiting on **in1** vs going to **in2**.  A fix using the current API would be by checking for _size()_ of the stream before calling the peek so that the number of  items could be found (I've added a peek timeout example below if it would be more useful/intuitive than _size()_ ). 

I can see a timeout being  better for some code (cleaner, easier to fit the paradigm). I propose having a function call variant that mimics the  current _peek()_ but has two parameters, one a reference to a flag, and two a std::chrono::duration of time. 


```cpp
using peek_timeout_t = std::chrono< /** some templates go here **/ >;
/** current definition **/
template< class T,
             typename std::enable_if< inline_alloc< T >::value >::type* = nullptr >
   T& peek( raft::signal *signal = nullptr );

/**
 * NOTE: there would of course be three of these, one for 
 * each allocation type, perhaps more.
 */
template< class T,
             typename std::enable_if< inline_alloc< T >::value >::type* = nullptr >
   T& peek( bool &timeout, const peek_timeout_t &&timeout, raft::signal *signal = nullptr );
```

To modify the given example for the _size()_ function I mentioned,  it would look something like this (also, I'm now entertaining the  idea of a simple _dataAvail_ function given that it would only take two ops to determine if data is avail). 

```cpp
auto &port_in1( input[ "in1" ] );
if( port_in1.size() > 0 )
{
std::cout << "in1: " << cnt << "\n";
                auto &a( port_in1.peek< big_t >() );
                std::cout << std::dec << a.i << " - " << std::hex << a.start << " - " << std::hex <<  
                    reinterpret_cast< std::uintptr_t >( &a.i ) << "\n";
                port_in1.recycle(1);

} /** end size check **/
```

**Comment by mr-j0nes** [comment]
Hi Jonathan,

Thanks for the reply. Firstly the raft::sleep would be something really good to have, I was wondering how much the sleep() system call was affecting the streaming flow.

Secondly particularly in my case the size() option is exactly what I need, it works like a charm. I don't think I would need a function with a timeout. Having the size() method referenced in the documentation would have been enough for me.

For my question I consider this matter close. Not sure if you want to keep it open for the raft::sleep idea?

Thanks again..

**Comment by jonathan-beard** [comment]
Will update the documentation. closing issue.
