### ISSUE TITLE
Remove dependency on boost

### ISSUE THREAD

**Issue by ymadzhunkov** [RaftLib/RaftLib#53]
Currently the entire projects depends on boost library. It looks like the only functionally that is used from boost is

        boost::core::demangle

The boost demangle is just a thin wrapper of include <cxxabi.h>. Removing dependency on boost will allow RaftLib to be easy to integrate. Currently, if boost 1.59 is not installed ( for example I have 1.58 on Ubuntu 16.04) the boost submodules are initialized. In our company we have strict  'no submodule in submodule' policy. So in order to remove boost dependency, I propose one of the following:

   * Replace boost demangle with RaftLib Demangle
   * Instead of reporting demangled name in exception, report mangled name.

I know that in most systems installing boost is not a big deal, but image I have an embedded computer like raspberry pi and only 4GB of disk space.

**Comment by jonathan-beard** [comment]
Hah. I totally Agree. I can go back to the version in the tree that wasn't dependent on boost, which coincidentally did have cxxabi directly. Turns out it makes portability a pain in some cases. To remove the boost dependency (and it is only the mangling last I checked), I'm okay with the mangled name vs. demangled. Can you produce a pull request for the change? If not, let me know and I'll see if I can find some time to cut out the lines and push it back.

**Comment by ymadzhunkov** [comment]
Hi, 
I am glad to help with that issue. I will produce a pull request by the end of the week.

**Comment by jonathan-beard** [comment]
Awesome, thank you!

**Comment by ymadzhunkov** [comment]
You can close the issue

**Comment by jonathan-beard** [comment]
yes, just wanted to test it out on the dev branch too. done :) will merge that one manually
