### ISSUE TITLE
Question: Memory allocation for very large element sizes?

### ISSUE THREAD

**Issue by vectronic** [RaftLib/RaftLib#60]
In the case of processing video, buffers for high-res video frames (e.g. uncompressed 4K with 12 bits per channel) can be very large. The way I understand Raft is that all FIFOs would need to allocate space for these frames (elements).

A. Would there be a limit to the element size before efficiencies in caching and locality break down e.g. the size of a cache line?

B. If so, if the element was a smaller wrapper object pointing to a global shared pool of pre-allocated frame buffers, I assume this would just shift the problem of caching and locality to the shared pool? And this could be even harder to coordinate if multiple kernels are making use of it...

**Comment by jonathan-beard** [comment]
>Would there be a limit to the element size before efficiencies in caching and locality break down >e.g. the size of a cache line?

By definition there is a limit to efficiencies for caching when the element size goes outside of the size of a single cache line. RaftLib by design has three different behavior for object allocation size. I'd like to understand the object structure a bit better to give a definitive answer...For small allocation (fundamental types or data structures less than a cache line size) the allocations are essentially in-place within the FIFO. As long as that FIFO structure between kernels exists at the current size, the data is read in place from producer to consumer. When objects are allocated (in C++, things with constructors vs. P.O.D types) then the constructor is called in-place to set up the structure before the user gets to use it. For items greater than a single cache line, RaftLib uses either the system slab allocator to allocate the large objects then passes around pointers to that object. That way the large allocations can exist across an entire topology vs. just at one FIFO. RaftLib handles passing the pointer from one kernel to the next safely, then discards it when that pointer is no longer in use. Another feature of the large allocation is that RaftLib inserts prefetch hints into the instruction stream for those large objects when they near the head of the queue for the consumer. That way, despite being a pointer, we parallelize as best as possible the memory access to those large objects. We don't do this for things that are less than a cache line size given that most next line pre-fetchers handle the FIFO pattern that's designed in RaftLib very very well (i.e., the follow-on data will always be in the cache for the consumer). This does create some pedantic worst case behavior with false sharing, some architectures do better than others with this. 

> If so, if the element was a smaller wrapper object pointing to a global shared pool of pre-allocated frame buffers, I assume this would just shift the problem of caching and locality to the shared pool? And this could be even harder to coordinate if multiple kernels are making use of it...

I think I answered this one in the last response. If there's a large frame buffer, RaftLib automatically creates a pool with automated pre-fetch hints that are transparent to the user. The pointer to those pools is passed around transparently and garbage collected when no longer in use. It's entirely transparent to the user when these pools are created, the only way you'll know is by doing sizeof(x) on the type you're allocating. When calling allocate on the port is when this behavior is kicked off. Push should also do it as well, when copying in a large object. I'll double check to make sure that's the case, but I'm pretty sure it is. The idea with keeping the pools managed by RaftLib is that there isn't a way for multiple kernels to step on each other by accessing the same data. However, given that glibc uses a nice slab allocator, the pool of memory is essentially managed by the OS. One thing I need to re-implement is the page management for these pools. Ideally I'd be able to call numa_page_move to create locality for the pool as it moves through the graph, right now first touch in Linux puts it on the NUMA node of first allocation. To fix the current behavior, I'd need to wrap the glibc allocator and use aligned memory...basically, each allocation would need to get a new page no matter how big the allocation or how small. 


To get a better idea of how this works, it'd be good to start with the [allocation traits header file](https://github.com/RaftLib/RaftLib/blob/master/raftinc/alloc_traits.tcc). This gives the definitions that enable the rest of the templates to decide which type of FIFO to instantiate. 

Going from the "outside" to the inside, looking at the [fifo.hpp](https://github.com/RaftLib/RaftLib/blob/master/raftinc/fifo.hpp) file we get some functions like this one:

```cpp
   template< class T,
             typename std::enable_if< ext_alloc< T >::value >::type* = nullptr >
   T& peek( raft::signal *signal = nullptr )
   {
      T **ptr( nullptr );
      local_peek( (void**)&ptr, signal );
      return( **ptr );
   }
```

That have to use the templates here to ensure that the correct pointer type is returned. In this case, if it's an external object that's created with the allocate function (it's created by default in a pool above a certain size. For really big objects, we get this type of construct in the fifo.hpp file since 
it's the last layer of object that actually "understands" what the object type is before we just get to bytes and addresses:

```cpp
   template < class T,
              class ... Args,
              typename std::enable_if< ext_alloc< T >::value >::type* = nullptr > 
   T& 
   allocate( Args&&... params )
   {
      T **ptr( nullptr );
      /** call blocks till an element is available **/
      local_allocate( (void**) &ptr );
      *ptr = new T( std::forward< Args >( params )... );
      return( **ptr );
   }
```

Then going to the [ringbuffer](https://github.com/RaftLib/RaftLib/blob/master/raftinc/ringbufferheap.tcc) itself, for the heap implementation, there are actually three distinct variants. You'll see comments like this throughout the file to help you find your way:

```cpp
/*********************************
 * INLINE CLASS ALLOC STARTS HERE
 *********************************/

template < class T >
class RingBufferBase<
    T,
    Type::Heap,
    typename std::enable_if< inl
```

If you're curious, for the external pool, the code looks like this:

```cpp
   virtual void  local_push( void *ptr, const raft::signal &signal )
   {
      for(;;)
      {
         /** data manager is for the ring buffer resizing **/
         (this)->datamanager.enterBuffer( dm::push );
         if( (this)->datamanager.notResizing() )
         {
            if( (this)->space_avail() > 0 )
            {
               break;
            }
         }
         (this)->datamanager.exitBuffer( dm::push );
         if( (this)->write_stats.bec.blocked == 0 )
         {
            (this)->write_stats.bec.blocked = 1;
         }
#if (defined NICE) && (! defined USEQTHREADS)
         std::this_thread::yield();
#if __x86_64
         __asm__ volatile("\
           pause"
           :
           :
           : );
#endif
#endif
#ifdef USEQTHREADS
         qthread_yield();
#endif
      }
      auto * const buff_ptr( (this)->datamanager.get() );
       const size_t write_index( Pointer::val( buff_ptr->write_pt ) );
      if( ptr != nullptr )
      {
          T *item( reinterpret_cast< T* >( ptr ) );
          T * temp( new (
            &buff_ptr->store[ write_index ]
          ) T( *item  ) );
          UNUSED( temp );
          (this)->write_stats.bec.count++;
       }
      buff_ptr->signal[ write_index ]         = signal;
       Pointer::inc( buff_ptr->write_pt );
      if( signal == raft::quit )
      {
         (this)->write_finished = true;
      }
      (this)->datamanager.exitBuffer( dm::push );
   }
```

Lastly, if we peek an externally allocated object. There's some code that enables prefetch
```cpp
   /**
    * local_peek() - look at a reference to the head of the
    * ring buffer.  This doesn't remove the item, but it
    * does give the user a chance to take a look at it without
    * removing.
    * @return T&
    */
   virtual void local_peek(  void **ptr, raft::signal *signal )
   {
      for(;;)
      {

         (this)->datamanager.enterBuffer( dm::peek );
         if( (this)->datamanager.notResizing() )
         {
            if( (this)->size() > 0  )
            {
               break;
            }
            else if( (this)->is_invalid() && (this)->size() == 0 )
            {
               throw ClosedPortAccessException(
                  "Accessing closed port with local_peek call, exiting!!" );
            }
         }
         (this)->datamanager.exitBuffer( dm::peek );
#if (defined NICE) && (! defined USEQTHREADS)
         std::this_thread::yield();
#if  __x86_64
         __asm__ volatile("\
           pause"
           :
           :
           : );
#endif
#endif
#ifdef USEQTHREADS
         qthread_yield();
#endif
      }
      auto * const buff_ptr( (this)->datamanager.get() );
      const size_t read_index( Pointer::val( buff_ptr->read_pt ) );
      if( signal != nullptr )
      {
         *signal = buff_ptr->signal[ read_index ];
      }
      //actual pointer
      auto ***real_ptr( reinterpret_cast< T*** >( ptr ) );
      *real_ptr = reinterpret_cast< T** >( &( buff_ptr->store[ read_index ] ) );
      /** prefetch first 1024  bytes **/
      //probably need to optimize this for each arch / # of
      //threads
      raft::prefetch< raft::READ,
                      raft::LOTS,
                      sizeof( T ) < sizeof( std::uintptr_t ) << 7 ?
                      sizeof( T ) : sizeof( std::uintptr_t ) << 7
                      >( **real_ptr );
      (this)->in_peek->insert( reinterpret_cast< ptr_t >( **real_ptr ) );
      return;
      /**
       * exitBuffer() called when recycle is called, can't be sure the
       * reference isn't being used until all outside accesses to it are
       * invalidated from the buffer.
       */
   }
```

There's two really important things going on here. First, there's a set (in_peek) that operates across each kernel in the run function that implements garbage collection, but that's called from the scheduler so the garbage collection calls are at the right times and can be coordinated with execution.

**Comment by jonathan-beard** [comment]
@vectronic, feel free to close if you're satisfied with the answer. 

-J

**Comment by vectronic** [comment]
Thank you so much for the in-depth answer. You've given me a lot to digest and I definitely have a better grasp on things now. Diagram was excellent as well.
